import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // globals.css нь app/ хуудасны шууд доор байх ёстой

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ${inter.className} -ийн ард зай авсан байгааг анзаараарай 👇
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
